
median_metric: 'error_any'

plots_to_genearte: 

  deduplication_with_defaults:
    function: get_main_result_plots
    sample_desc: deduplication_defaults
    dedupe_defaults: True
    framework: deduplication
    benchmark_lines: median
    benchmark_uncertainty_shading: False
    any_or_corr: any
    metrics: ['error', 'prc', 'tpr']
  
  record_linkage_with_defaults:
    function: get_main_result_plots
    sample_desc: record_linkage_defaults
    dedupe_defaults: True
    framework: record_linkage
    benchmark_lines: median
    benchmark_uncertainty_shading: False
    any_or_corr: any
    all_or_nem: all
    metrics: ['error', 'prc', 'tpr']

  deduplication_with_defaults_with_shading:
    function: get_main_result_plots
    sample_desc: deduplication_defaults
    dedupe_defaults: True
    framework: deduplication
    benchmark_lines: median
    benchmark_uncertainty_shading: True
    any_or_corr: any
    metrics: ['error', 'prc', 'tpr']
  
  record_linkage_with_defaults_with_shading:
    function: get_main_result_plots
    sample_desc: record_linkage_defaults
    dedupe_defaults: True
    framework: record_linkage
    benchmark_lines: median
    benchmark_uncertainty_shading: True
    any_or_corr: any
    all_or_nem: all
    metrics: ['error', 'prc', 'tpr']
  
  deduplication:
    function: get_main_result_plots
    sample_desc: deduplication_optimized
    dedupe_defaults: False
    framework: deduplication
    benchmark_lines: median
    benchmark_uncertainty_shading: False
    any_or_corr: any
    metrics: ['error', 'prc', 'tpr']

  record_linkage:
    function: get_main_result_plots
    sample_desc: record_linkage_optimized
    dedupe_defaults: False
    framework: record_linkage
    benchmark_lines: median
    benchmark_uncertainty_shading: False
    any_or_corr: any
    metrics: ['error', 'prc', 'tpr']

  deduplication_with_shading:
    function: get_main_result_plots
    sample_desc: deduplication_optimized
    dedupe_defaults: False
    framework: deduplication
    benchmark_lines: median
    benchmark_uncertainty_shading: True
    any_or_corr: any
    metrics: ['error', 'prc', 'tpr']

  record_linkage_with_shading:
    function: get_main_result_plots
    sample_desc: record_linkage_optimized
    dedupe_defaults: False
    framework: record_linkage
    benchmark_lines: median
    benchmark_uncertainty_shading: True
    any_or_corr: any
    metrics: ['error', 'prc', 'tpr']

  sample_size_deduplication:
    function: get_sample_size_plots
    sample_desc: deduplication
    framework: deduplication
    any_or_corr: any
    metrics: ['error', 'prc', 'tpr']
    diff_markers: False
